services:
  api:
    image: ${API_DOCKER_IMAGE_TAG:-pedalo-ui-api}
    build:
      context: .
      dockerfile: ./PedaloWebApp.UI.Api/Dockerfile
      x-bake:
        cache-from:
          - type=gha,scope=api
        cache-to:
          - type=gha,scope=api,mode=max
    healthcheck:
      test: curl --fail http://api/api/translations/languages || exit 1
      interval: 5s
      retries: 30
      start_period: 20s
      timeout: 10s
    ports:
      - 40281:80
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__AppDbContext=Server=mssql;Database=neolution_pedalo;User ID=sa;Password=Test1234!;TrustServerCertificate=True;Encrypt=True;
      - SiteConfig__ClientBaseUrl=http://client
    depends_on:
      data-initializer:
        condition: service_completed_successfully
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    image: ${CLIENT_DOCKER_IMAGE_TAG:-pedalo-ui-client}
    build:
      context: .
      dockerfile: ./PedaloWebApp.UI.Client/Dockerfile
      x-bake:
        cache-from:
          - type=gha,scope=client
        cache-to:
          - type=gha,scope=client,mode=max
    ports:
      - 31546:80
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://client || exit 1
      interval: 5s
      retries: 10
      start_period: 20s
      timeout: 10s
    environment:
      - NODE_CONFIG_ENV=ci
    extra_hosts:
      - "host.docker.internal:host-gateway"

  data-initializer:
    image: ${docker_image_tag_data_initializer:-pedalo-tools-data-initalizer}
    build:
      context: .
      dockerfile: ./PedaloWebApp.Tools.DataInitializer/Dockerfile
      x-bake:
        cache-from:
          - type=gha,scope=data-initializer
        cache-to:
          - type=gha,scope=data-initializer,mode=max
    environment:
      - DOTNET_ENVIRONMENT=CI
    depends_on:
      mssql:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cypress-tests:
    image: ${docker_image_tag_cypress_tests:-pedalo-ui-cypress}
    build:
      context: .
      dockerfile: ./PedaloWebApp.FunctionalTests/Dockerfile
      x-bake:
        cache-from:
          - type=gha,scope=cypress-tests
        cache-to:
          - type=gha,scope=cypress-tests,mode=max
    depends_on:
      client:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: cypress run --spec ${CYPRESS_SPEC:-**/*.cy.ts}
    environment:
      - CYPRESS_BASE_URL=http://client
      - CYPRESS_dbServer=mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234!
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Test1234!" -Q "SELECT 1" -C || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
