# reference: https://prettier.io/docs/en/options.html
printWidth: 140
useTabs: false
tabWidth: 2
endOfLine: auto
semi: true
singleQuote: false
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always
