name: Deploy Preview To Production

on:
  workflow_dispatch:

env:
  GCP_PROJECT_NAME: gcp-project-name-prodcution
  GCP_CLOUD_RUN_API: pedalo-api-production
  GCP_CLOUD_RUN_CLIENT: pedalo-client-production
  GCP_CLIENT_URL: https://your-client-url
  GCP_API_URL: https://your-api-url

  WORKLOAD_IDENTITY_PROVIDER: projects/651591561863/locations/global/workloadIdentityPools/gh-actions-pool/providers/gh-actions-provider
  SERVICE_ACCOUNT: pipeline@gcp-project-name-prodcution.iam.gserviceaccount.com

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Authenticate Docker"
        run: gcloud auth configure-docker -q

      - name: "Tagging Docker images"
        run: |
          docker pull eu.gcr.io/${{ env.GCP_PROJECT_NAME }}/ui-api:preview-latest
          docker pull eu.gcr.io/${{ env.GCP_PROJECT_NAME }}/ui-client:preview-latest

          docker tag eu.gcr.io/${{ env.GCP_PROJECT_NAME }}/ui-api:preview-latest eu.gcr.io/${{ env.GCP_PROJECT_NAME }}/ui-api:latest
          docker tag eu.gcr.io/${{ env.GCP_PROJECT_NAME }}/ui-client:preview-latest eu.gcr.io/${{ env.GCP_PROJECT_NAME }}/ui-client:latest

          docker push eu.gcr.io/${{ env.GCP_PROJECT_NAME }}/ui-api:latest
          docker push eu.gcr.io/${{ env.GCP_PROJECT_NAME }}/ui-client:latest

      - name: "Deploy API on Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "${{ env.GCP_CLOUD_RUN_API }}"
          image: "eu.gcr.io/${{ env.GCP_PROJECT_NAME }}/ui-api:latest"
          region: "europe-west6"
          env_vars: |
            SiteConfig__ClientBaseUrl=${{ env.GCP_CLIENT_URL }}

      - name: "Update Traffic for api"
        run: |
          gcloud run services update-traffic ${{ env.GCP_CLOUD_RUN_API }} --region=europe-west6 --to-latest --remove-tags=preview

      - name: "Deploy Client on Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "${{ env.GCP_CLOUD_RUN_CLIENT }}"
          image: "eu.gcr.io/${{ env.GCP_PROJECT_NAME }}/ui-client:latest"
          region: "europe-west6"
          env_vars: |
            publicRuntimeConfig__apiBaseUrl=${{ env.GCP_API_URL }}

      - name: "Update Traffic for client"
        run: |
          gcloud run services update-traffic ${{ env.GCP_CLOUD_RUN_CLIENT }} --region=europe-west6 --to-latest --remove-tags=preview
